Test web cadastro
STC-TEAM-PROJECT/robot-web-stc pull request #1
Opened 2022-05-19 12:44 UTC by LucasFelice

rs.

2022-05-19 20:04 UTC, uLucasFraga requested changes
subiu um arquivo .gitignore sem nada?

2022-05-19 20:05 UTC, uLucasFraga commented on base.robot
> +${IMAGE_SERVEREST}                      //img[contains(@class,'imagem')]
colocar isso no base? não entendi.

2022-05-19 20:06 UTC, uLucasFraga requested changes
você está subindo o mesmo requirements do outro projeto?

tem necessidade de subir as mesmas libs?
e o selenium?

2022-05-19 20:07 UTC, uLucasFraga requested changes
esses arquivos /log, não devem subir.
precisam ser ignorados.

2022-05-19 20:07 UTC, uLucasFraga commented on tests/TestUsuarios.robot
> +Documentation           User test for users.
user? ou login?
não entendi.

2022-05-19 20:09 UTC, uLucasFraga commented on tests/integration-test/keywords/usuarios/Usuarioskw.robot
> +Go page register user
porque isso está na KW de CARRINHOS?
se é USERS?

2022-05-19 20:10 UTC, uLucasFraga requested changes
não se deve criar uma estrutura de INTEGRATION, porque os testes aqui precisam ser de UI.
Integration == services == API.

2022-05-19 21:47 UTC, uLucasFraga commented
Porfavor, verificar as mudanças que se fazem necessárias.

2022-05-27 22:53 UTC, uLucasFraga commented
Irei aceitar para depois melhorarmos juntos.

2022-05-27 22:53 UTC, uLucasFraga approved these changes

2022-06-01 13:21 UTC, RafaelFelice approved these changes
remove logs and evidence, create more test scenarios.

2022-06-02 11:24 UTC, merged